name: Angular 12 Build
on:
  push:
    branches:
      - main
      - actions-pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Angular CLI
      run: npm install -g @angular/cli@12

    - name: Install Dependencies
      run: npm i --prefix ./Frontend

    - name: Interpolate environment variables
      shell: bash
      id: interpolate
      run: |
         pwd
         ls -la
         node -v
         npm -v
         cd /home/runner/work/_actions/
         ls -la
         # cd /home/runner/work/_actions/FoodOrderingApp
         # ls -la

    - name: Build
      #run: npm run build
      run: npm run serve-dev --prefix /home/runner/work/FoodOrderingApp/FoodOrderingApp/Frontend

    - name: Archive Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
