name: Angular 12 Build
on:
  push:

env:
  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: "fe-angular-orderingapp"
  CLOUDFRONT_DISTRIBUTION_ID: "E1TYUO4EA9KMOE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Angular CLI
      run: npm install -g @angular/cli@12

    - name: Install Dependencies
      run: npm i

    - name: Build
      run: npm run build-dev 

    - name: Archive Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

    - name: Install AWS CLI
      run: |
        sudo apt-get update && \
        sudo apt-get install -y python3-pip && \
        pip3 install awscli

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        S3_BUCKET_NAME: ${{ env.S3_BUCKET_NAME }}
      run: |
        aws s3 sync /home/runner/work/FoodOrderingApp/FoodOrderingApp/dist/food-ordering-app s3://${{ env.S3_BUCKET_NAME }} --acl public-read --delete --cache-control max-age=31536000,public

    - name: Invalidate CloudFront Cache
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        CLOUDFRONT_DISTRIBUTION_ID: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
